2017-04-08 09:32:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: IO Exception: "IOException reading Sample Data - item.csv"; SQL statement:
INSERT INTO ITEM SELECT * FROM CSVREAD('Sample Data - item.csv') [90028-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.tools.Csv.convertException(Csv.java:598)
	at org.h2.tools.Csv.read(Csv.java:197)
	at org.h2.expression.Function.getValueForColumnList(Function.java:2705)
	at org.h2.table.FunctionTable.<init>(FunctionTable.java:66)
	at org.h2.command.Parser.readTableFilter(Parser.java:1249)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1897)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2045)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1891)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1709)
	at org.h2.command.Parser.parseSelect(Parser.java:1697)
	at org.h2.command.Parser.parseInsert(Parser.java:1111)
	at org.h2.command.Parser.parsePrepared(Parser.java:413)
	at org.h2.command.Parser.parse(Parser.java:317)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.prepareCommand(Parser.java:254)
	at org.h2.engine.Session.prepareLocal(Session.java:561)
	at org.h2.engine.Session.prepareCommand(Session.java:502)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1203)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: Sample Data - item.csv (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.h2.store.fs.FilePathDisk.newInputStream(FilePathDisk.java:321)
	at org.h2.store.fs.FileUtils.newInputStream(FileUtils.java:218)
	at org.h2.tools.Csv.initRead(Csv.java:316)
	at org.h2.tools.Csv.readResultSet(Csv.java:219)
	at org.h2.tools.Csv.read(Csv.java:195)
	... 25 more
2017-04-08 09:42:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: IO Exception: "IOException reading Downloads/Sample Data - item.csv"; SQL statement:
INSERT INTO ITEM SELECT * FROM CSVREAD('Downloads/Sample Data - item.csv') [90028-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.tools.Csv.convertException(Csv.java:598)
	at org.h2.tools.Csv.read(Csv.java:197)
	at org.h2.expression.Function.getValueForColumnList(Function.java:2705)
	at org.h2.table.FunctionTable.<init>(FunctionTable.java:66)
	at org.h2.command.Parser.readTableFilter(Parser.java:1249)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1897)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2045)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1891)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1709)
	at org.h2.command.Parser.parseSelect(Parser.java:1697)
	at org.h2.command.Parser.parseInsert(Parser.java:1111)
	at org.h2.command.Parser.parsePrepared(Parser.java:413)
	at org.h2.command.Parser.parse(Parser.java:317)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.prepareCommand(Parser.java:254)
	at org.h2.engine.Session.prepareLocal(Session.java:561)
	at org.h2.engine.Session.prepareCommand(Session.java:502)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1203)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: Downloads\Sample Data - item.csv (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.h2.store.fs.FilePathDisk.newInputStream(FilePathDisk.java:321)
	at org.h2.store.fs.FileUtils.newInputStream(FileUtils.java:218)
	at org.h2.tools.Csv.initRead(Csv.java:316)
	at org.h2.tools.Csv.readResultSet(Csv.java:219)
	at org.h2.tools.Csv.read(Csv.java:195)
	... 25 more
2017-04-08 09:43:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: IO Exception: "IOException reading Downloads/Sample Data - item.csv"; SQL statement:
INSERT INTO ITEM SELECT * FROM CSVREAD('Downloads/Sample Data - item.csv') [90028-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.tools.Csv.convertException(Csv.java:598)
	at org.h2.tools.Csv.read(Csv.java:197)
	at org.h2.expression.Function.getValueForColumnList(Function.java:2705)
	at org.h2.table.FunctionTable.<init>(FunctionTable.java:66)
	at org.h2.command.Parser.readTableFilter(Parser.java:1249)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1897)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2045)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1891)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1709)
	at org.h2.command.Parser.parseSelect(Parser.java:1697)
	at org.h2.command.Parser.parseInsert(Parser.java:1111)
	at org.h2.command.Parser.parsePrepared(Parser.java:413)
	at org.h2.command.Parser.parse(Parser.java:317)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.prepareCommand(Parser.java:254)
	at org.h2.engine.Session.prepareLocal(Session.java:561)
	at org.h2.engine.Session.prepareCommand(Session.java:502)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1203)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: Downloads\Sample Data - item.csv (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.h2.store.fs.FilePathDisk.newInputStream(FilePathDisk.java:321)
	at org.h2.store.fs.FileUtils.newInputStream(FileUtils.java:218)
	at org.h2.tools.Csv.initRead(Csv.java:316)
	at org.h2.tools.Csv.readResultSet(Csv.java:219)
	at org.h2.tools.Csv.read(Csv.java:195)
	... 25 more
2017-04-08 09:46:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'The Dinosaur That Wins Customers' (ITEM: DEWEYID INT NOT NULL)"; SQL statement:
INSERT INTO ITEM SELECT * FROM CSVREAD('C:\Users\Andrew\Downloads\Sample Data - item.csv') -- row #2 ('130478', '5', 'The Dinosaur That Wins Customers', 'Drama', '2006') [22018-193]
2017-04-08 09:59:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "TIMESTAMP" constant "2/6/2017"; SQL statement:
INSERT INTO HOLDS SELECT * FROM CSVREAD('C:\Users\Andrew\Downloads\Sample Data - holds.csv') -- row #2 ('917062', '917062', '4', '2/6/2017', '5') [22007-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:122)
	at org.h2.value.Value.convertTo(Value.java:930)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.addRow(Insert.java:189)
	at org.h2.command.dml.Insert.insertRows(Insert.java:172)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2/6/2017
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:140)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:120)
	... 16 more
2017-04-08 10:03:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "TIMESTAMP" constant "1/4/2017"; SQL statement:
INSERT INTO CHECKOUT SELECT * FROM CSVREAD('C:\Users\Andrew\Downloads\Sample Data - checkout.csv') -- row #2 ('917062', '130478', '5', '1/4/2017', '1/12/2017', '2/4/2017') [22007-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:122)
	at org.h2.value.Value.convertTo(Value.java:930)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.addRow(Insert.java:189)
	at org.h2.command.dml.Insert.insertRows(Insert.java:172)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 1/4/2017
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:140)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:120)
	... 16 more
2017-04-08 10:09:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO CHECKOUT SELECT * FROM CSVREAD('C:\Users\Andrew\Downloads\Sample Data - checkout.csv') [21002-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:282)
	at org.h2.command.Parser.prepareCommand(Parser.java:259)
	at org.h2.engine.Session.prepareLocal(Session.java:561)
	at org.h2.engine.Session.prepareCommand(Session.java:502)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1203)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-04-08 10:09:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "TIMESTAMP" constant "null"; SQL statement:
INSERT INTO CHECKOUT SELECT * FROM CSVREAD('C:\Users\Andrew\Downloads\Sample Data - checkout.csv') -- row #9 ('788278', '977256', '4', '2017-01-20', 'null', '2017-02-20') [22007-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:122)
	at org.h2.value.Value.convertTo(Value.java:930)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.addRow(Insert.java:189)
	at org.h2.command.dml.Insert.insertRows(Insert.java:172)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: null
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:140)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:120)
	... 16 more
2017-04-16 14:37:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE VIEW OVERDUE_BOOKSAS SELECT[*] ITEM_TITLE, DEWEY_ID, ITEM_NUMBERFROM CHECKOUTWHERE ENDDATE = NULL AND DUEDATE >  CURDATE() "; expected "., COMMENT, (, AS"; SQL statement:
Create view overdue_booksAs select item_title, dewey_id, item_numberFrom checkoutWhere endDate = null and dueDate >  curDate() [42001-194]
2017-04-16 14:38:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "ITEM_TITLE" not found; SQL statement:
Create view overdue_books As select item_title, dewey_id, item_number From checkout Where endDate = null and dueDate >  curDate() [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:146)
	at org.h2.command.dml.Select.prepare(Select.java:853)
	at org.h2.command.Parser.parseCreateView(Parser.java:4888)
	at org.h2.command.Parser.parseCreate(Parser.java:4245)
	at org.h2.command.Parser.parsePrepared(Parser.java:364)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at pterodactyl.View.viewOverdueBooks(View.java:98)
	at pterodactyl.View.LibrarianOptions(View.java:66)
	at pterodactyl.View.<init>(View.java:36)
	at pterodactyl.Main.main(Main.java:11)
2017-04-16 14:42:03 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at pterodactyl.View.<init>(View.java:25)
	at pterodactyl.Main.main(Main.java:11)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
2017-04-16 15:01:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
Create view overdue_books As select deweyid, itemnumber From checkout Where endDate = null and dueDate >  curDate() [90002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Prepared.query(Prepared.java:212)
	at org.h2.command.CommandContainer.query(CommandContainer.java:113)
	at org.h2.command.Command.executeQuery(Command.java:201)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:79)
	at pterodactyl.View.viewOverdueBooks(View.java:99)
	at pterodactyl.View.LibrarianOptions(View.java:67)
	at pterodactyl.View.<init>(View.java:37)
	at pterodactyl.Main.main(Main.java:11)
2017-04-16 15:05:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: View "OVERDUE_BOOKS" already exists; SQL statement:
Create view overdue_books As select deweyid, itemnumber From checkout Where endDate = null and dueDate >  curDate() [90038-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateView.update(CreateView.java:87)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at pterodactyl.View.viewOverdueBooks(View.java:101)
	at pterodactyl.View.LibrarianOptions(View.java:67)
	at pterodactyl.View.<init>(View.java:37)
	at pterodactyl.Main.main(Main.java:11)
2017-04-16 15:11:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CURDATE[*]() "; expected "COMMIT, CREATE, CALL, CHECKPOINT, COMMENT, {"; SQL statement:
curDate() [42001-194]
2017-04-16 15:13:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Function "DATE" not found; SQL statement:
SELECT * FROM CHECKOUT WHERE DATE(dueDate) < curDate() [90022-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readJavaFunction(Parser.java:2471)
	at org.h2.command.Parser.readFunction(Parser.java:2523)
	at org.h2.command.Parser.readTerm(Parser.java:2860)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2087)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1928)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1746)
	at org.h2.command.Parser.parseSelect(Parser.java:1734)
	at org.h2.command.Parser.parsePrepared(Parser.java:447)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-04-16 15:18:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO CHECKOUT VALUES(917062, 130479, 6, CURDATE(),,[*] CURDATE()) "; expected "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"; SQL statement:
INSERT INTO CHECKOUT VALUES(917062, 130479, 6, curDate(),, curDate()) [42001-194]
2017-04-16 15:18:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO CHECKOUT VALUES(917062, 130479, 6, CURDATE(),,[*] CURDATE()) "; expected "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"; SQL statement:
INSERT INTO CHECKOUT VALUES(917062, 130479, 6, curDate(),, curDate()) [42001-194]
2017-04-16 15:19:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO CHECKOUT (PATRONID,DEWEYID,ITEMNUMBER,BEGINNINGDATE,DUEDATE)VALUES(917062, 130479, 6, CURDATE(),,[*] CURDATE()) "; expected "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"; SQL statement:
INSERT INTO CHECKOUT (PATRONID,DEWEYID,ITEMNUMBER,BEGINNINGDATE,DUEDATE)VALUES(917062, 130479, 6, curDate(),, curDate()) [42001-194]
2017-04-16 15:24:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "0" for parameter "columnIndex" [90008-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:228)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3189)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3217)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:326)
	at pterodactyl.View.viewOverdueBooks(View.java:105)
	at pterodactyl.View.LibrarianOptions(View.java:67)
	at pterodactyl.View.<init>(View.java:37)
	at pterodactyl.Main.main(Main.java:11)
2017-04-16 15:39:45 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at pterodactyl.View.<init>(View.java:26)
	at pterodactyl.Main.main(Main.java:11)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
2017-04-16 15:50:43 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at pterodactyl.View.<init>(View.java:26)
	at pterodactyl.Main.main(Main.java:11)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Andrew/workspace/PterodactylProject/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
2017-04-16 15:54:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DEWEYID, ITEMNUMBER, TITLE FROM ITEM WHERE TITLE LIKE %[*]B% "; expected "SELECT, FROM, WITH"; SQL statement:
Select deweyID, ItemNumber, title from item where title like %b% [42001-194]
2017-04-16 15:55:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM ITEM WHERE TITLE LIKE %[*]B% "; expected "SELECT, FROM, WITH"; SQL statement:
SELECT * FROM ITEM where title like %b% [42001-194]
2017-04-16 15:58:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "What You Should Have Asked Your Teachers About Dinosaur" [22018-194]
2017-04-16 16:14:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
Update holds Set endDate = curDate() Where patronID = 917062 and DeweyID = 917062 and itemNumber = 4 and (endDate > curDate() or endDate is null) [90002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Prepared.query(Prepared.java:212)
	at org.h2.command.CommandContainer.query(CommandContainer.java:113)
	at org.h2.command.Command.executeQuery(Command.java:201)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:79)
	at pterodactyl.View.removeHoldOnItem(View.java:251)
	at pterodactyl.View.PatronOptions(View.java:294)
	at pterodactyl.View.<init>(View.java:44)
	at pterodactyl.Main.main(Main.java:11)
